In [1]:
#importing libraries
import tensorflow as tf
import numpy as np
from keras.models import Sequential
from keras.layers import Dense,Dropout,BatchNormalization,Activation,Flatten
from keras.layers.convolutional import Conv2D,MaxPooling2D
from keras.constraints import maxnorm
import matplotlib.pyplot as plt
from keras.utils import np_utils

In [2]:
#importing cifar 10 dataset
from keras.datasets import cifar10

In [3]:
(X_train, y_train),(X_test,y_test) = cifar10.load_data()

In [4]:
print(X_train[0])

[[[ 59  62  63]
  [ 43  46  45]
  [ 50  48  43]
  ...
  [158 132 108]
  [152 125 102]
  [148 124 103]]

 [[ 16  20  20]
  [  0   0   0]
  [ 18   8   0]
  ...
  [123  88  55]
  [119  83  50]
  [122  87  57]]

 [[ 25  24  21]
  [ 16   7   0]
  [ 49  27   8]
  ...
  [118  84  50]
  [120  84  50]
  [109  73  42]]

 ...

 [[208 170  96]
  [201 153  34]
  [198 161  26]
  ...
  [160 133  70]
  [ 56  31   7]
  [ 53  34  20]]

 [[180 139  96]
  [173 123  42]
  [186 144  30]
  ...
  [184 148  94]
  [ 97  62  34]
  [ 83  53  34]]

 [[177 144 116]
  [168 129  94]
  [179 142  87]
  ...
  [216 184 140]
  [151 118  84]
  [123  92  72]]]


In [5]:
#normalize the inputs from 0-255 to between 0 to 1 dividing by 255
X_train = X_train / 255
X_test = X_test / 255

In [6]:
y_train = np_utils.to_categorical(y_train)
y_test = np_utils.to_categorical(y_test)
class_num = y_test.shape[1]

In [7]:
model = Sequential()

In [8]:
model.add(Conv2D(filters = 32, activation='relu', kernel_size=(3,3) , input_shape=(32,32,3)))
model.add(Dropout(0.2))
model.add(BatchNormalization())
model.add(Conv2D(filters = 64, activation='relu', kernel_size=(3,3)))
model.add(Dropout(0.2))
model.add(BatchNormalization())


model.add(Conv2D(filters = 128, activation='relu', kernel_size=(3,3)))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.2))
model.add(BatchNormalization())

model.add(Conv2D(filters = 256, activation='relu', kernel_size=(3,3)))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.2))
model.add(BatchNormalization())

model.add(Conv2D(filters = 512, activation='relu', kernel_size=(3,3)))
model.add(Dropout(0.2))
model.add(BatchNormalization())

In [9]:
model.add(Flatten())
model.add(Dropout(0.2))

In [10]:
model.add(Dense(64, activation='relu', kernel_constraint=maxnorm(3)))
model.add(Dropout(0.2))
model.add(BatchNormalization())

model.add(Dense(10, activation='relu', kernel_constraint=maxnorm(3)))
model.add(Dropout(0.2))
model.add(BatchNormalization())

In [11]:
model.add(Dense(class_num, activation='softmax'))

In [12]:
model.compile(optimizer='adam',loss = 'categorical_crossentropy',metrics=['accuracy'])

In [13]:
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 30, 30, 32)        896       
                                                                 
 dropout (Dropout)           (None, 30, 30, 32)        0         
                                                                 
 batch_normalization (BatchN  (None, 30, 30, 32)       128       
 ormalization)                                                   
                                                                 
 conv2d_1 (Conv2D)           (None, 28, 28, 64)        18496     
                                                                 
 dropout_1 (Dropout)         (None, 28, 28, 64)        0         
                                                                 
 batch_normalization_1 (Batc  (None, 28, 28, 64)       256       
 hNormalization)                                        

In [14]:
model.fit(X_train,y_train,epochs=5,batch_size=64)

Epoch 1/5
782/782 [==============================] - 577s 735ms/step - loss: 1.7741 - accuracy: 0.3645
Epoch 2/5
782/782 [==============================] - 635s 811ms/step - loss: 1.3400 - accuracy: 0.5301
Epoch 3/5
782/782 [==============================] - 615s 786ms/step - loss: 1.1560 - accuracy: 0.6036
Epoch 4/5
782/782 [==============================] - 690s 883ms/step - loss: 1.0460 - accuracy: 0.6444
Epoch 5/5
782/782 [==============================] - 637s 814ms/step - loss: 0.9656 - accuracy: 0.6771


In [15]:
scores = model.evaluate(X_test,y_test,verbose=0)
print("Accuracy:",scores)

Accuracy: [0.8175530433654785, 0.7214000225067139]
