In [16]:
#importing libraries
import tensorflow as tf
import numpy as np
from keras.models import Sequential
from keras.layers import Dense,Dropout,BatchNormalization,Activation,Flatten
from keras.layers.convolutional import Conv2D,MaxPooling2D
from keras.constraints import maxnorm
import matplotlib.pyplot as plt
from keras.utils import np_utils

In [17]:
#importing cifar 10 dataset
from keras.datasets import cifar10

In [18]:
(X_train, y_train),(X_test,y_test) = cifar10.load_data()

In [19]:
print(X_train[0])

[[[ 59  62  63]
  [ 43  46  45]
  [ 50  48  43]
  ...
  [158 132 108]
  [152 125 102]
  [148 124 103]]

 [[ 16  20  20]
  [  0   0   0]
  [ 18   8   0]
  ...
  [123  88  55]
  [119  83  50]
  [122  87  57]]

 [[ 25  24  21]
  [ 16   7   0]
  [ 49  27   8]
  ...
  [118  84  50]
  [120  84  50]
  [109  73  42]]

 ...

 [[208 170  96]
  [201 153  34]
  [198 161  26]
  ...
  [160 133  70]
  [ 56  31   7]
  [ 53  34  20]]

 [[180 139  96]
  [173 123  42]
  [186 144  30]
  ...
  [184 148  94]
  [ 97  62  34]
  [ 83  53  34]]

 [[177 144 116]
  [168 129  94]
  [179 142  87]
  ...
  [216 184 140]
  [151 118  84]
  [123  92  72]]]


In [20]:
#normalize the inputs from 0-255 to between 0 to 1 dividing by 255
X_train = X_train / 255
X_test = X_test / 255

In [21]:
y_train = np_utils.to_categorical(y_train)
y_test = np_utils.to_categorical(y_test)
class_num = y_test.shape[1]

In [22]:
model = Sequential()

In [23]:
model.add(Conv2D(filters = 32, activation='relu', kernel_size=(3,3) , input_shape=(32,32,3)))
model.add(Dropout(0.5))
model.add(BatchNormalization())

model.add(Conv2D(filters = 64, activation='relu', kernel_size=(3,3)))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.5))
model.add(BatchNormalization())

model.add(Conv2D(filters = 128, activation='relu', kernel_size=(3,3)))
model.add(Dropout(0.5))
model.add(BatchNormalization())

In [24]:
model.add(Flatten())
model.add(Dropout(0.5))

In [25]:
model.add(Dense(256, activation='relu', kernel_constraint=maxnorm(3)))
model.add(Dropout(0.5))
model.add(BatchNormalization())

model.add(Dense(128, activation='relu', kernel_constraint=maxnorm(3)))
model.add(Dropout(0.5))
model.add(BatchNormalization())

In [26]:
model.add(Dense(class_num, activation='softmax'))

In [27]:
model.compile(optimizer='adam',loss = 'categorical_crossentropy',metrics=['accuracy'])

In [28]:
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_3 (Conv2D)           (None, 30, 30, 32)        896       
                                                                 
 dropout_6 (Dropout)         (None, 30, 30, 32)        0         
                                                                 
 batch_normalization_5 (Batc  (None, 30, 30, 32)       128       
 hNormalization)                                                 
                                                                 
 conv2d_4 (Conv2D)           (None, 28, 28, 64)        18496     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 14, 14, 64)       0         
 2D)                                                             
                                                                 
 dropout_7 (Dropout)         (None, 14, 14, 64)       

In [29]:
model.fit(X_train,y_train,epochs=5,batch_size=64)

Epoch 1/5
782/782 [==============================] - 220s 280ms/step - loss: 1.8992 - accuracy: 0.3202
Epoch 2/5
782/782 [==============================] - 234s 299ms/step - loss: 1.4841 - accuracy: 0.4596
Epoch 3/5
782/782 [==============================] - 245s 314ms/step - loss: 1.3547 - accuracy: 0.5149
Epoch 4/5
782/782 [==============================] - 228s 292ms/step - loss: 1.2659 - accuracy: 0.5516
Epoch 5/5
782/782 [==============================] - 228s 292ms/step - loss: 1.2172 - accuracy: 0.5691


In [30]:
scores = model.evaluate(X_test,y_test,verbose=0)
print("Accuracy:",scores)

Accuracy: [1.3389967679977417, 0.5198000073432922]
